title: Silvie Strauß # your name (or website title) here
# logo: "/images/Masterküken.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  [sɪlvi ʃtʁa͜ʊs]
  <br><br>
  <br><br>
  <font size="2"> silvie.strauss[at]uni-leipzig.de </font>

  <a href="pdf/CV.pdf">CV</a> 
  
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
